### PR TITLE
Couple Bug Fixes

### LINKED ISSUE #122: [Bug] Ability to add multiple connection addresses in one listener
Feature Request 

It would be great to have the ability to add multiple connect addresses for a single listener. The grunt could randomly connect to one of the listed connect addresses. When this address is burnt, it will connect to one of the remaining addresses.

The platform allows you to add more than one connect address but only saves ones. I got a bit excited when I saw that it allows more than one.

Feature would be cool to have. Its coming in CS....#justsaying

### LINKED ISSUE #123: [Bug] CompilationErrors displayed for subsequent tasks after the failure of one task
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
I created a Task which had some bugs in it - due to which C# compilation failed on the Grunt when I ran it. Now, when I attempt to execute any other task including a valid shellCmd on a grunt, I am stuck with "CompilerException: CompilationErrors: " errors and the previous C# compilation errors are shown. Is there a way to reset the Grunt so it does not attempt to compile the old task and just executes the specified command?

**To Reproduce**
1. Go to Tasks
2. Click on Create
3. Create the task below which has C# bugs in it with a single optional param called 'serverIP': 

```
using SharpUp;
using SharpSploit.Execution;

public static class Task
{
    public static string Execute(string serverIp = "")
    {
        string output = "";
        string command = "";
        try
        {   
            output += "\n"
            output += "\n"
            output += "==== Get hostname via 'hostname' command ===="
            output += "\n"
            output += "\n"
            command = "hostname";
            output += Shell.ShellCmdExecute(command);

            output += "\n"
            output += "\n"
            output += "==== Get current user and permissions via 'whoami' command===="
            output += "\n"
            output += "\n"
            command = "whoami /all";
            output += Shell.ShellCmdExecute(command);

            output += "\n"
            output += "\n"
            output += "=== SharpUp: Running Privilege Escalation Checks similar to PowerUp from Powersploit ==="
            output += "\n"
            output += "\n"
            TextWriter realStdOut = Console.Out;
            TextWriter realStdErr = Console.Error;
            TextWriter stdOutWriter = new StringWriter();
            TextWriter stdErrWriter = new StringWriter();
            Console.SetOut(stdOutWriter);
            Console.SetError(stdErrWriter);
            bool auditMode = args.Contains("audit", StringComparer.CurrentCultureIgnoreCase);
            Program.PrivescChecks(auditMode);
            Console.Out.Flush();
            Console.Error.Flush();
            Console.SetOut(realStdOut);
            Console.SetError(realStdErr);

            output += stdOutWriter.ToString();
            output += stdErrWriter.ToString();
        }
        catch (Exception e) { output += e.GetType().FullName + ": " + e.Message + Environment.NewLine + e.StackTrace; }
        return output;
    }
}
```
4. Now go to interact for a Grunt and run the task above a couple of times.
5. Subsequent execution of any other task including 'WhoAmI' show the compilation errors  for the task above.

**Expected behavior**
The task should abort if it has bugs in it and other tasks should not be affected.

**Screenshots**
Attached below.

**Covenant Server Information:**
 - OS: Kali Linux Rolling
 - Docker or Native: Docker

**Browser Information:**
 - Browser: Firefox 
 - Version: 60.6.3esr(64bit)

**Target Information (System that implant is running on):**
 - OS: Windows 7 SP1
 - Version [e.g. 22]: 6.1.7600

### LINKED ISSUE #137: [Bug] Sort Grunts based on 24-hour time
Right now the Grunts on Dashboard are sorted by time, but not based on the 24 hour clock which results in something like this:

Where a Grunt that dies at 6 AM is sorted higher that one in-use at 4 PM

### PR DESCRIPTION
**Pull request by fasetto**
Fix #122 bug related to multiple connection adresses issue
Fix #137 grunt last checked-in field sorting issue on table

### CODE REVIEW

**Comment by mubix** [comment]
Looking forward to this being committed ;-)

**Comment by cobbr** [comment]
Thanks @fasetto  for these bug fixes, it is much appreciated!

Thought I would give you a heads up on why this hasn't been merged yet. Covenant v0.5 is going to be moving to Blazor, which means that the 2 files you have changed here actually no longer exist in the next version 🙁 

I thought v0.5 would be coming a bit sooner than development has allowed it to come. I may merge this in here soon so everyone can take advantage of your fixes in the meantime before the next version is out. I'll be sure that your fixes are incorporated into v0.5 as well 🙂

**Comment by fasetto** [comment]
I didn't knew, but its great then.
Looking forward to see the Blazor version of this project.

**Comment by cobbr** [comment]
thanks @fasetto!

**Pull request merged**
