### PR TITLE
New Persistence Tasks

### PR DESCRIPTION
**Pull request by rasta-mouse**
Added new Persistence Tasks for SharpSploit's Autorun, Startup and WMI Persistence classes.  Added lots of help text within the `Description` field - not sure how you feel about the format or if there's a "better" way to add this much detail.

image

### CODE REVIEW

**Comment by itpropro** [comment]
After implementing all the persistence tasks by myself, I realized that this PR already exists 🙈 Great work @rasta-mouse!

**Comment by rasta-mouse** [comment]
lol oh no @itpropro  🤦‍♂️

**Comment by cobbr** [comment]
Sorry @itpropro and @rasta-mouse, I'll get this merged sometime this week.

**Comment by cobbr** [comment]
Or I'll do it now 🙂 

Excellent work @rasta-mouse!

**Pull request merged**
